// Generated by CoffeeScript 1.6.2
(function() {
  var date, day, month, year;

  date = new Date();

  month = date.getMonth() + 1 < 10 ? '0' + (date.getMonth() + 1) : date.getMonth() + 1;

  day = date.getDate() < 10 ? '0' + date.getDate() : date.getDate();

  year = date.getYear() % 100;

  $('#date').text(month + '/' + day + '/' + year + '  ' + date.toLocaleTimeString());

  (function($) {
    return $.fn.drags = function(opt) {
      var $el;

      opt = $.extend({
        handle: "",
        cursor: "move"
      }, opt);
      if (opt.handle === "") {
        $el = this;
      } else {
        $el = this.find(opt.handle);
      }
      return $el.css('cursor', opt.cursor).on('mousedown', function(e) {
        var $drag, drg_h, drg_w, pos_x, pos_y, z_idx;

        if (opt.handle === "") {
          $drag = $(this).addClass('draggable');
        } else {
          $drag = $(this).addClass('active-handle').parent().addClass('draggable');
        }
        z_idx = $drag.css('z-index');
        drg_h = $drag.outerHeight();
        drg_w = $drag.outerWidth();
        pos_y = $drag.offset().top + drg_h - e.pageY;
        pos_x = $drag.offset().left + drg_w - e.pageX;
        $drag.css('z-index', 1000).parents().on('mousemove', function(e) {
          return $('.draggable').offset({
            top: e.pageY + pos_y - drg_h,
            left: e.pageX + pos_x - drg_w
          }).on('mouseup', function() {
            return $(this).removeClass('draggable').css('z-index', z_idx);
          });
        });
        return e.preventDefault();
      }).on('mouseup', function() {
        if (opt.handle === "") {
          return $(this).removeClass('draggable');
        } else {
          return $(this).removeClass('active-handle').parent().removeClass('draggable');
        }
      });
    };
  })($);

  $('#settingsPopup').on('click', 'input[type="submit"]', function(e) {
    var phoneLogin;

    e.preventDefault();
    phoneLogin = $('#phone-login').val();
    return $.ajax({
      url: "./options.php",
      data: {
        setPhoneLogin: phoneLogin
      },
      success: function(data) {
        $('#settingsPopup').data('user', data['user']);
        $('#settingsPopup').data('pass', data['pass']);
        $('#settingsPopup').data('server-ip', data['set_server_ip']);
        return $('#settingsPopup').data('monitor-phone', data['setPhoneLogin']);
      },
      dataType: "json"
    });
  });

  $.ajax({
    url: "./options.php",
    success: function(data) {
      var begin, element, selectCampaigns, t, userGroups, _i, _j, _len, _len1, _ref, _ref1;

      $('#settingsPopup').data('user', data['user']);
      $('#settingsPopup').data('pass', data['pass']);
      $('#settingsPopup').data('server-ip', data['get_server_ip']);
      $('#settingsPopup').data('monitor-phone', data['getPhoneLogin']);
      $('#settingsPopup #phone-login').val(data['getPhoneLogin']);
      $('#webphone').data('user', data['webphone_name']);
      $('#webphone').data('pass', data['webphone_pass']);
      $('#webphone').data('server-ip', data['webphone_ip']);
      selectCampaigns = "";
      _ref = data['selectCampaigns'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        selectCampaigns += '<option>' + element + '</option>';
      }
      $('#select-campaigns').html(selectCampaigns);
      userGroups = "";
      _ref1 = data['userGroups'];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        element = _ref1[_j];
        userGroups += '<option>' + element + '</option>';
      }
      $('#select-usergroups').html(userGroups);
      t = data['time'] * 1000;
      begin = new Date(t);
      return setInterval(function() {
        month = begin.getMonth() + 1 < 10 ? '0' + (begin.getMonth() + 1) : begin.getMonth() + 1;
        day = begin.getDate() < 10 ? '0' + begin.getDate() : begin.getDate();
        year = begin.getYear() % 100;
        $('#date').text(month + '/' + day + '/' + year + '  ' + begin.toLocaleTimeString());
        return begin.setTime(begin.valueOf() + 1000);
      }, 1000);
    },
    dataType: "json"
  });

  $('#sectionA').on('click', '#settings', function() {
    return $('#settingsPopup').show();
  });

  $('#options').on('hover', function() {
    $('#options').toggleClass('darkBlue');
    return $('#optionsPopup').toggle();
  });

  $('#optionsPopup').on('hover', 'a', function() {
    $('#options').toggleClass('darkBlue');
    $('#optionsPopup').toggle();
    return $(this).toggleClass('darkBlue');
  });

  $('#settingsPopup').on('click', 'a.close', function(e) {
    e.preventDefault();
    return $('#settingsPopup').hide();
  });

  $('#activeResourcesTable').on('click', 'a#closeActiveResourcesForm', function(e) {
    e.preventDefault();
    return $('#activeResourcesForm').remove();
  });

  $('#sectionA').on('click', '#webphone', function(e) {
    var ip, pass, user;

    e.preventDefault();
    user = $('#webphone').data('user');
    pass = $('#webphone').data('pass');
    ip = $('#webphone').data('server-ip');
    $('#webphonePopup').css('visibility', 'visible');
    return $.ajax({
      url: './webphone/adminphoneapplet.php?serveraddress=' + ip + '&username=' + user + '&password=' + pass,
      success: function(data) {
        return $('#webphonePopup .closable').html(data);
      },
      dataType: "html"
    });
  });

  $('#webphonePopup').on('click', '.close', function(e) {
    e.preventDefault();
    $('#webphonePopup .closable').empty();
    return $('#webphonePopup').css('visibility', 'hidden');
  });

  $('#webphonePopup').on('click', '.minimize', function(e) {
    e.preventDefault();
    $('#webphonePopup .closable').css('visibility', 'hidden');
    $('#webphonePopup').animate({
      height: '-=430px'
    });
    $('#webphonePopup .minimize').addClass('open');
    return $('#webphonePopup .minimize').removeClass('minimize');
  });

  $('#webphonePopup').on('click', '.open', function(e) {
    e.preventDefault();
    $('#webphonePopup .closable').css('visibility', 'visible');
    $('#webphonePopup').animate({
      height: '+=430px'
    });
    $('#webphonePopup .open').addClass('minimize');
    return $('#webphonePopup .open').removeClass('open');
  });

  $('#alert, #webphonePopup, #settingsPopup').drags();

}).call(this);
