// Generated by CoffeeScript 1.6.2
(function() {
  var chart, data, h, w, x, y;

  data = [70.37, 0, 29.59, 0.04];

  w = 20;

  h = 80;

  x = d3.scale.linear().domain([0, 1]).range([0, w]);

  y = d3.scale.linear().domain([0, 100]).rangeRound([0, h]);

  chart = d3.select('#sectionC div.closable').append('svg').attr('class', 'chart').attr('width', w * data.length - 1).attr('height', h);

  chart.selectAll('rect').data(data).enter().append('rect').attr('x', function(d, i) {
    return x(i) - 0.5;
  }).attr('y', function(d) {
    return h - y(d) - 0.5;
  }).attr('width', w).attr('height', function(d) {
    return y(d);
  });

  chart.append("line").attr("x1", 0).attr("x2", w * data.length).attr("y1", h - .5).attr("y2", h - .5).style("stroke", "#000");

}).call(this);
